# 设置基础镜像
FROM nginx
# 定义作者
MAINTAINER yao guan shou



#清理缓存
# ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache
# # 将dist文件中的内容复制到 /usr/share/nginx/html/ 这个目录下面
# COPY dist/  /usr/share/nginx/html/


# #进入到app目录下面，类似cd
# RUN echo '进入/usr/share/nginx/html/目录'
# WORKDIR /usr/share/nginx/html/

# RUN echo '出来/目录'
# WORKDIR /
# COPY nginx.conf /etc/nginx/nginx.conf
# COPY nginx.conf /etc/nginx/conf/nginx.conf
# ARG
# 覆盖默认配置
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# ARG arg1=123456
# ARG arg2=NGINX_PORT
# ARG arg3=CLIENT

# RUN echo '参数'
# RUN echo '${NGINX_HOST}'
# RUN echo NGINX_PORT > 12
# RUN echo arg1
 

RUN echo 'entry镜像build构建成功'
 